// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgrUbNH6Q1zwyedH1CmsYZxVkzBrP1HKU',
    appId: '1:454396059628:web:de908ddbf746e6d5e62ac9',
    messagingSenderId: '454396059628',
    projectId: 'flutterprojects-50e69',
    authDomain: 'flutterprojects-50e69.firebaseapp.com',
    storageBucket: 'flutterprojects-50e69.appspot.com',
    measurementId: 'G-B43SCB2K64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAET171WtzTUksMzVf9HKL8uRk175Fs6fA',
    appId: '1:454396059628:android:41d7e6d7d5a9e797e62ac9',
    messagingSenderId: '454396059628',
    projectId: 'flutterprojects-50e69',
    storageBucket: 'flutterprojects-50e69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDze1w_yLLczUEeRQ7g_F1TJ-VWqhDh2U',
    appId: '1:454396059628:ios:dc1a515e42fbd0b1e62ac9',
    messagingSenderId: '454396059628',
    projectId: 'flutterprojects-50e69',
    storageBucket: 'flutterprojects-50e69.appspot.com',
    iosBundleId: 'com.example.mindlinkApp',
  );
}
